name: Meu Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Compilar o projeto .NET
        run: dotnet build

      - name: Executar testes
        run: dotnet test

      - name: Executar ação de push
        run: echo "Executando ação acionada por push"

  scheduled:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Executar ação agendada
        run: echo "Executando ação agendada a cada hora"
